# Generated by Django 6.0.6 on 2026-06-30 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='Pendente', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='main.status'),
        ),
    ]
