# Generated by Django 6.0.6 on 2026-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='permite_edicao_usuario',
            field=models.BooleanField(default=False, help_text='Permite que usuários comuns editem esta tarefa', verbose_name='Permitir edição por usuários'),
        ),
    ]
