# Generated by Django 6.0.6 on 2026-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_task_permite_edicao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='permite_edicao_usuario',
            field=models.BooleanField(default=True, help_text='Permite que usuários comuns editem esta tarefa', verbose_name='Permitir edição por usuários'),
        ),
    ]
